#spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#      bindings:
#        output:
#          destination: my-topic
#          producer:
#            partitionKeyExpression: headers['partitionKey']
#            partitionCount: 2